name: Release feature KrmGen
permissions:
  contents: write
on:
  push:
    branches:
      - 'feature/**'

jobs:
  publishFeature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
          check-latest: true

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/snapshot',
              sha: context.sha
            })

      - name: Build feature platforms
        run: |
          sudo apt-get install rhash -y
          make all-dist CLI_PLATFORMS="darwin-amd64 linux-amd64"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*
          prerelease: true
          fail_on_unmatched_files: true
          name: snapshot
